### ISSUE TITLE
Can't smelt tin ore

### ISSUE THREAD

**Issue by MathiasMelk** [Clownvin/Just-A-Few-More-Ores#2]
Minecraft 1.12.2 - I have Railcraft installed, which has a tin ore and ingot, but I can't find tin ores (railcraft ones) so I installed this mod to see if it would seve as a substitute, but the tin ore from this mod doesn't smelt, also, on the JEI, I can only find bronze, mithril and platinum ingots.

**Comment by Clownvin** [comment]
There are no copper or tin ingots, just bronze. You combine the two ores in a crafting menu, and smelt the combined "dust".
